## Initialise
init:
	echo 'init terraform'
	terraform init
.PHONY: init

## Apply
apply:
	echo 'apply terraform'
	terraform apply -auto-approve
.PHONY: apply

## Destory
destroy:
	echo 'destroy terraform'
	terraform destroy -auto-approve
.PHONY: destroy
